"""create initial health resource tables

Revision ID: 78d602363090
Revises: 
Create Date: 2026-09-24 13:55:45.160594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d602363090'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federated_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('participating_phcs', sa.Integer(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('global_mse', sa.Float(), nullable=False),
    sa.Column('global_rmse', sa.Float(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_number')
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_medicine_id'), 'medicines', ['medicine_id'], unique=True)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phc_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phcs_phc_id'), 'phcs', ['phc_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phc_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phc_id'], ['phcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_medicine_id'), 'alerts', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_alerts_phc_id'), 'alerts', ['phc_id'], unique=False)
    op.create_table('demand_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phc_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_demand', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phc_id'], ['phcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phc_id', 'medicine_id', 'date', name='uq_demand_phc_medicine_date')
    )
    op.create_index(op.f('ix_demand_history_date'), 'demand_history', ['date'], unique=False)
    op.create_index(op.f('ix_demand_history_medicine_id'), 'demand_history', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_demand_history_phc_id'), 'demand_history', ['phc_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phc_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('expired_quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phc_id'], ['phcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phc_id', 'medicine_id', name='uq_inventory_phc_medicine')
    )
    op.create_index(op.f('ix_inventory_medicine_id'), 'inventory', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_inventory_phc_id'), 'inventory', ['phc_id'], unique=False)
    op.create_table('redistribution_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('source_phc_id', sa.Integer(), nullable=False),
    sa.Column('destination_phc_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_phc_id'], ['phcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_phc_id'], ['phcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redistribution_requests_destination_phc_id'), 'redistribution_requests', ['destination_phc_id'], unique=False)
    op.create_index(op.f('ix_redistribution_requests_medicine_id'), 'redistribution_requests', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_redistribution_requests_source_phc_id'), 'redistribution_requests', ['source_phc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redistribution_requests_source_phc_id'), table_name='redistribution_requests')
    op.drop_index(op.f('ix_redistribution_requests_medicine_id'), table_name='redistribution_requests')
    op.drop_index(op.f('ix_redistribution_requests_destination_phc_id'), table_name='redistribution_requests')
    op.drop_table('redistribution_requests')
    op.drop_index(op.f('ix_inventory_phc_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_medicine_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_demand_history_phc_id'), table_name='demand_history')
    op.drop_index(op.f('ix_demand_history_medicine_id'), table_name='demand_history')
    op.drop_index(op.f('ix_demand_history_date'), table_name='demand_history')
    op.drop_table('demand_history')
    op.drop_index(op.f('ix_alerts_phc_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_medicine_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_phcs_phc_id'), table_name='phcs')
    op.drop_table('phcs')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_medicines_medicine_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('federated_rounds')
    # ### end Alembic commands ###
