"""add ai decision audit

Revision ID: b188be4b9185
Revises: 78d602363090
Create Date: 2026-09-24 18:12:10.312416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b188be4b9185'
down_revision: Union[str, Sequence[str], None] = '78d602363090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decision_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('phc_id', sa.String(length=50), nullable=True),
    sa.Column('medicine_id', sa.String(length=50), nullable=True),
    sa.Column('medicine_name', sa.String(length=255), nullable=True),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('predicted_daily_demand', sa.Float(), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('estimated_stock_days', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('recommended_order_quantity', sa.Float(), nullable=True),
    sa.Column('shortage_quantity', sa.Float(), nullable=True),
    sa.Column('surplus_quantity', sa.Float(), nullable=True),
    sa.Column('expired_stock_ratio_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decision_audits_created_at'), 'ai_decision_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_decision_audits_id'), 'ai_decision_audits', ['id'], unique=False)
    op.create_index(op.f('ix_ai_decision_audits_medicine_id'), 'ai_decision_audits', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_ai_decision_audits_phc_id'), 'ai_decision_audits', ['phc_id'], unique=False)
    op.create_index(op.f('ix_ai_decision_audits_request_id'), 'ai_decision_audits', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_decision_audits_request_id'), table_name='ai_decision_audits')
    op.drop_index(op.f('ix_ai_decision_audits_phc_id'), table_name='ai_decision_audits')
    op.drop_index(op.f('ix_ai_decision_audits_medicine_id'), table_name='ai_decision_audits')
    op.drop_index(op.f('ix_ai_decision_audits_id'), table_name='ai_decision_audits')
    op.drop_index(op.f('ix_ai_decision_audits_created_at'), table_name='ai_decision_audits')
    op.drop_table('ai_decision_audits')
    # ### end Alembic commands ###
